name: 'publish-latest-release'

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish_artifact:
    name: 'Publish Artifact as Latest Release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2              
      - name: 'Generate OCI ORM Stack zip file'
        run: |
          cd ${{ github.workspace }}/build-orm
          sh -x build.sh
      - name: 'Generate pre-release for ORM click to deploy button'
        uses: eine/tip@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'orm-deploy'
          files: |
            ${{ github.workspace }}/build-orm/orm.zip
