name: 'publish-orm-stack'

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish_artifact:
    name: 'Publish Release for ORM Stack'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2              
      - name: 'Generate ORM Stack zip file'
        run: |
          cd ${{ github.workspace }}/build-orm
          sh -x build.sh
      - name: 'Publish Release'
        uses: "marvinpinto/action-automatic-releases@v1.1.2"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          #Artifact will be available for download at: https://github.com/<organization>/<repository>/releases/download/<automatic_release_tag>/<zip file>
          #E.g. https://github.com/oracle-quickstart/oci-github-actions-runner/releases/download/orm-deploy/orm.zip
          automatic_release_tag: "orm-deploy"
          prerelease: true
          title: "Latest Resource Manager Stack"
          files: |
            ${{ github.workspace }}/build-orm/orm.zip