name: 'publish-latest-release'

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish_artifact:
    name: 'Publish Artifact as Latest Release'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: build-orm
    steps:
        uses: actions/checkout@v2      
      - name: 'Generate ORM Stack zip file'
        run: |
          pwd
          sh -x build.sh
          ls -la
      - name: 'Upload Artifact'
        uses: eine/tip@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'latest'
          files: |
            ./*.zip
